sudo: required

language: python

services:
    - docker

before_install:
    - docker build -t linux-docker-travis-learn .
    - docker run -d --name app linux-docker-travis-learn
    - docker ps -a

script:
    - docker exec app python -m unittest discover

after_script:
    - docker rm -f app
